### ISSUE TITLE
A12 Magisk Hidden apps crash

### ISSUE THREAD

**Issue by Kellwaxx11** [nongthaihoang/custom_font_installer#1]
Hi, firstly thank you for this , its the only way i was able to get a fully functional font change on Android 12
Device: OnePlus 5 (cheeseburger)
Rom: Xtended A12
Magisk v23

the problem is after flashing CFI in magisk and reboot, all my banking apps and apps i hide within magisk hide doesnt open anymore
examples: Revolut, Binance, Play Store

I hope you can find whats breaking it , i will try to take logs and get back asap

Thank you

**Comment by Kellwaxx11** [comment]
[logfile.txt](https://github.com/nongthaihoang/custom_font_installer/files/7718100/logfile.txt)

**Comment by nongthaihoang** [comment]
Known Magisk vs Android 12 issue. Work around here:
Install this AFDKO extension along with CFI:
https://gitlab.com/nongthaihoang/oh_my_font/-/tree/dev#afdko-source
Instructions on how to install extensions here:
https://gitlab.com/nongthaihoang/oh_my_font/-/wikis/home#extensions

**Comment by nongthaihoang** [comment]
This is Magisk vs Android 12 issue and can't be addressed from module sides. Hence, Close!
