### ISSUE TITLE
Google-related Settings crashing/not opening with CFI installed

### ISSUE THREAD

**Issue by cyanGalaxy** [nongthaihoang/custom_font_installer#2]
With CFI installed (using default configs), Google Settings, Find My Device, and other Google-related Settings don't open for me.

I use a Pixel-based Custom ROM. It has built-in font customisation, which **does not** change the font for the Settings Category Title, but Google Settings can be opened when using one of the built-in fonts.

CFI however **does** change the font for the Settings Category Title, **but many Google-Settings crash** with CFI installed.

**This leads me to believe that this specific Title-font *needs* to be Google Sans.**

Can I exclude this type of text/font so that Google Settings can open again with CFI ? Or do you know other way to fix Google-Settings crashing?

Here are 2 screenshots, first image is Comic Sans by my ROM (excludes Title-font, Google Settings work), and the second image is "Segoe Variable" using CFI (includes Title-font, Google Settings crash)
![Screenshot_20220930-172919_Settings](https://user-images.githubusercontent.com/49559300/193307810-bcbe03eb-fc2d-457f-bee1-765dbbd85c8a.png)
![Screenshot_20220930-173229_Settings](https://user-images.githubusercontent.com/49559300/193307812-b9da9b43-1c0b-43b0-8ec7-cb7c4c488cde.png)

**Comment by nongthaihoang** [comment]
Magisk and CFI alone does not cause Google settings or any apps to force close. You probably have other modules installed, i.e., Universal Safetynet Fix, other root-hiding modules. And most importantly, Your ROM is Android 12 and later. I am just a font module maker. I'm not capable of fixing this Magisk vs Android problem. Fortunately, there's a workaround that works for most people. Please check the issue #1.

**Comment by cyanGalaxy** [comment]
> Magisk and CFI alone does not cause Google settings or any apps to force close. You probably have other modules installed, i.e., Universal Safetynet Fix, other root-hiding modules. And most importantly, Your ROM is Android 12 and later. I am just a font module maker. I'm not capable of fixing this Magisk vs Android problem. Fortunately, there's a workaround that works for most people. Please check the issue #1.

Thank you for the reply! That was exactly my issue! Using AFDKO worked!
I did see the closed issue, but thought it was a different issue.

This also explains why I had this issue with other Font Modules.

Thanks for your time & for making OhMyFont and CFI! I will close this issue.
