### ISSUE TITLE
KernelSU support

### ISSUE THREAD

**Issue by Kellwaxx11** [nongthaihoang/custom_font_installer#3]
could you please modify the script to support KernelSU module installation, for me its failing on the spoof part
Android 13 Rom
May 2023 security patch
![Screenshot_20230517-152311_KernelSU](https://github.com/nongthaihoang/custom_font_installer/assets/43542334/4331e724-1df5-4988-9332-c10b0d7fadf0)
 Many thanks in advance

**Comment by nongthaihoang** [comment]
Have not been on GitHub for a while.
Unfortunately, even if I want to try KernelSU, I can't install it on my device (Stock Pixel 5).

**Comment by nongthaihoang** [comment]
Since I've been inactive for a while. I'm gonna close all the issues and start over. Please create another if you want.
