### ISSUE TITLE
Choosable Lockscreen font option.

### ISSUE THREAD

**Issue by hndrk-themer** [nongthaihoang/custom_font_installer#4]
I don't know, if its possible to add the options for a specific different Lockscreen font. named like clock.ttf in the CFI folder which gets used to replace the GoogleSansClock font. Would be greatbto have that option.

**Comment by nongthaihoang** [comment]
It has. Set `LSC = cust` and put a `lsc.ttf` font to OMF folder.

**Comment by hndrk-themer** [comment]
oh i didnt know, the custom LSC doesnt seem to work tho,
am on Pixel June update (qpr3), latest afdko

![Screenshot_20230721-115438](https://github.com/nongthaihoang/custom_font_installer/assets/84930289/7be3d971-508b-44ac-86d1-f815ce6ab564)
![Screenshot_20230721-115459](https://github.com/nongthaihoang/custom_font_installer/assets/84930289/ff191592-08a0-4b71-9694-db602e867fc3)
![Screenshot_20230721-115514](https://github.com/nongthaihoang/custom_font_installer/assets/84930289/8d743422-697b-49bf-9009-7997b74bba73)

**Comment by nongthaihoang** [comment]
I need the Magisk install log and font file.

**Comment by hndrk-themer** [comment]
[magisk_install_log_2023-07-21T12.22.37.log](https://github.com/nongthaihoang/custom_font_installer/files/12122635/magisk_install_log_2023-07-21T12.22.37.log)

and 

[lsc.zip](https://github.com/nongthaihoang/custom_font_installer/files/12122647/lsc.zip)

**Comment by nongthaihoang** [comment]
Working on it.

**Comment by nongthaihoang** [comment]
Since I've been inactive for a while. I'm gonna close all the issues and start over. Please create another if you want.
