### ISSUE TITLE
Google play store crashes on android 14

### ISSUE THREAD

**Issue by jisanag** [nongthaihoang/custom_font_installer#9]
Only one font file is added to zip (ur.ttf or ss.ttf). After installing through magisk, fonts are applied correctly. But with this play store starts crashing. 

If module is disabled/removed, play store works correctly.

**Comment by leeann-chu** [comment]
I have the same problem ^

**Comment by changkanny** [comment]
I had the same issue, but I resolved it using the method described in [#1](https://github.com/nongthaihoang/custom_font_installer/issues/1#issuecomment-994832687).

**Comment by nongthaihoang** [comment]
The answer above is the current workaround.
